# Generated by Django 4.0 on 2022-01-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='college_learnt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertise',
            name='skill_mentor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
