# Generated by Django 4.0 on 2022-01-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_expertise_college_learnt_expertise_skill_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='college_learnt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='skill_mentor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
