# Generated by Django 4.0 on 2022-01-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_expertise_college_learnt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='media/team/')),
                ('full_name', models.CharField(max_length=100)),
                ('thought', models.TextField()),
            ],
        ),
    ]
