# Generated by Django 4.0 on 2022-01-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/team/'),
        ),
    ]
