# Generated by Django 4.0 on 2022-01-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_alter_teammember_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/members/'),
        ),
    ]
