# Generated by Django 4.0 on 2022-01-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_alter_teammember_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email_address',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
