# Generated by Django 4.0 on 2022-01-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_expertise_creative_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='creative_default',
        ),
    ]
