# Generated by Django 4.0 on 2022-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_remove_expertise_creative_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_design', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='creative_design',
        ),
    ]
