# Generated by Django 4.0 on 2022-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_creativedesign_remove_expertise_creative_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyselfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='images/me1.jpg', upload_to='media/images/')),
                ('full_name', models.CharField(default='Jeckonia Onyango', max_length=100)),
                ('course_doing', models.CharField(max_length=100)),
                ('side_course', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('school_abbr', models.CharField(max_length=100)),
                ('personal_stat', models.TextField()),
                ('personal_cv', models.FileField(blank=True, null=True, upload_to='media/cvs/')),
            ],
        ),
    ]
