# Generated by Django 4.0 on 2022-01-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_myselfmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_desc', models.TextField()),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='media/projects/')),
                ('project_link', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='myselfmodel',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myselfmodel',
            name='email_address',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myselfmodel',
            name='phone_num',
            field=models.IntegerField(default=254745547755, max_length=12),
        ),
    ]
