# Generated by Django 4.0 on 2022-01-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_myproject_myselfmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myselfmodel',
            name='school_link',
            field=models.URLField(default='https://www.jkuat.ac.ke'),
        ),
    ]
