# Generated by Django 4.0 on 2022-01-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_myselfmodel_school_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myselfmodel',
            old_name='side_course',
            new_name='side_hobby',
        ),
    ]
