# Generated by Django 4.0 on 2022-01-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_rename_side_course_myselfmodel_side_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myselfmodel',
            name='phone_num',
            field=models.IntegerField(default=254745547755),
        ),
    ]
