# Generated by Django 4.0 on 2022-01-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_alter_myselfmodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='project_category',
            field=models.CharField(choices=[('WEB DEV', 'Web Development'), ('HACKING', 'Hacking'), ('Programing', 'Programing'), ('UI/UX', 'Design')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
