# Generated by Django 4.0 on 2022-01-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_myproject_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='project_category',
            field=models.CharField(choices=[('WEB DEVELOPMENT', 'Web Development'), ('HACKING', 'Hacking'), ('PROGRAMMING', 'Programing'), ('UI/UX', 'Design')], max_length=100),
        ),
    ]
