# Generated by Django 4.0 on 2022-01-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_alter_myproject_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myproject',
            old_name='project_link',
            new_name='project_tw_link',
        ),
        migrations.AddField(
            model_name='myproject',
            name='project_yt_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
