# Generated by Django 4.0 on 2022-01-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_rename_project_link_myproject_project_tw_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myproject',
            old_name='project_yt_link',
            new_name='project_iG_link',
        ),
    ]
