# Generated by Django 4.0 on 2022-01-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0024_myselfmodel_home_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myselfmodel',
            name='marquee_text',
            field=models.CharField(default='Hey guys welcome to my dynamic django website', max_length=200),
        ),
        migrations.AlterField(
            model_name='myselfmodel',
            name='home_img',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
