# Generated by Django 4.0 on 2022-01-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0025_myselfmodel_marquee_text_alter_myselfmodel_home_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myselfmodel',
            name='marquee_text',
            field=models.CharField(default='Hey guys welcome to my dynamic django website', max_length=1000),
        ),
    ]
