# Generated by Django 4.0 on 2022-01-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0026_alter_myselfmodel_marquee_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myselfmodel',
            name='marquee_text',
            field=models.TextField(default='Hey guys welcome to my dynamic django website'),
        ),
    ]
