# Generated by Django 4.0 on 2022-01-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0027_alter_myselfmodel_marquee_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myselfmodel',
            old_name='marquee_text',
            new_name='marquee_text_home',
        ),
        migrations.AddField(
            model_name='myselfmodel',
            name='marquee_text_proj',
            field=models.TextField(default='Vaccination has numerous benefits'),
        ),
    ]
