# Generated by Django 4.0 on 2022-01-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0028_rename_marquee_text_myselfmodel_marquee_text_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='myselfmodel',
            name='marquee_text_serv',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='myselfmodel',
            name='marquee_text_home',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='myselfmodel',
            name='marquee_text_proj',
            field=models.TextField(default=''),
        ),
    ]
