# Generated by Django 4.0 on 2022-01-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0029_service_myselfmodel_marquee_text_serv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_icon',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
