# Generated by Django 4.0 on 2022-01-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0030_service_service_desc_service_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_icon',
            new_name='service_icon_name',
        ),
    ]
